services:
  - type: web
    name: mini-website-builder-backend
    env: docker
    plan: free
    repo: https://github.com/kesharg/mini-website-builder-backend-api
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: YOUR_DB_NAME
      - key: DB_USERNAME
        value: YOUR_DB_USERNAME
      - key: DB_PASSWORD
        value: YOUR_DB_PASSWORD
